### ISSUE TITLE
Re-connection with paired device is failing

### ISSUE THREAD

**Issue by Karry** [R1tschY/harbour-sailfishconnect#44]
Hi. I am using KDE connect 1.4.0 (Kubuntu 20.10) and Sailfish connect build from source (today) on SFOS 4.0.1.45. When I pair with my notebook, everything works fine. But when I terminate applicatin on the phone or restart the phone or connection just lost, it is not able to connect again. KDE daemon just prints error about certificate:
```
$ LC_ALL=C /usr/lib/x86_64-linux-gnu/libexec/kdeconnectd --replace 
kdeconnect.core: Disconnecting due to fatal SSL Error:  "The issuer certificate of a locally looked up certificate could not be found"
kdeconnect.core: Disconnecting due to fatal SSL Error:  "No certificates could be verified"
```

I need to unpair devices and pair them every time...

**Comment by Karry** [comment]
Interesting, problem disappeared when I removed old configuration... 
```
mv  .config/harbour-sailfishconnect .config/harbour-sailfishconnect.backup
```
Should I investigate more deeper? Do you have some suspect?

**Comment by R1tschY** [comment]
I fixed it yesterday with 81a6d8208bd0865dfa67cd411eefb89348a86db9. Can you please check if you are using the latest version?
Please remove all `*.pem` files in `.config/harbour-sailfishconnect` before testing.

The problem is that the certificate is generated with wrong information. When problem occurs a second time please attach the `.config/harbour-sailfishconnect/certifacte.pem` file or check it on your own: `openssl x509 -in certificate.pem -text -noout` should contain `CA:TRUE, pathlen:0` in output.

**Comment by Karry** [comment]
Yes, it is working... (with old configuration, but without key and certificate)

So, same problem will have everyone that will upgrade from 0.5.1 to 0.6.0, right? It would be great to have some code for migration, or at least mention it in changelog...

**Comment by R1tschY** [comment]
It should work with an upgrade from 0.5.1, because the problem is only the generation of the certificate. It was broken after 0.5.1 when I migrated to use kdeconnect-kde as submodule.

**Comment by Karry** [comment]
Great. Thank you for explanation :-)
