### ISSUE TITLE
clipboard sync problem from jolla to pc

### ISSUE THREAD

**Issue by paolomi** [R1tschY/harbour-sailfishconnect#7]
version: sailfishconnect 0.1
OS: sailfishOS 2.2.0.29

There is a sync problem from jolla to pc: I make a selection on my jolla1 and in klipper there is an empty entry.

vice versa it works fine: I make a selection on pc and the clipboard of sailfish changes correctly.

**Comment by R1tschY** [comment]
This is a known issue. I should document it. SailfishOS does not send changes in the clipboard to all applications. Only the application that owns the foreground window can read the current clipboard. This might be because of application isolation.

The workaround is to open the Sailfish Connect window after copying. Then the changed clipboard is recognized.

**Comment by paolomi** [comment]
i didn't know: thanks a lot for your workaround: it works! :) Document it in the application (pulley-menu - Tips) and then close this issue. Many thanks for everything! Bye :-)

**Comment by R1tschY** [comment]
Should be fixed with: f696bb77ee21355659f7250f0a94c85212a3f6d5

**Comment by R1tschY** [comment]
Since version 0.4: clipboard content must explicitly pushed in gui.
